version: "3.7"
services:
  postgres:
    image: postgres:12.3-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: camunda
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
